version: 0.2
env:
  variables:
    APP_NAME: "x-in-a-row-auth"
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - cd identityServer
      - echo install process started
      - npm install
      - npm install -g serverless
      - serverless plugin install -n serverless-stage-manager
      - serverless plugin install -n serverless-plugin-common-excludes
      - serverless plugin install -n serverless-plugin-include-dependencies
  build:
    commands:
      - echo build process started now
      - sls deploy
  post_build:
    commands:
      - echo serverless deploy completed